/**
 * ============================================================
 * CATALOG — every product and collection on the storefront.
 * ============================================================
 *
 * EDIT ME: To add a product, copy any block below and change the
 * fields. To clone this store for a different genre (candles,
 * ceramics, pet gear…), replace this file's contents and update
 * `content/site.config.ts` — nothing in components/ needs to change.
 *
 * Images are Pexels CDN URLs (free license, no attribution needed).
 * `px(photoId, width, height)` builds a cropped CDN URL.
 * Replace with your own product photography by swapping URLs or
 * pointing at files in /public.
 */
import type { Collection, Product } from "@/lib/types";
import { px } from "./site.config";

export const collections: Collection[] = [
  {
    id: "col-hair",
    slug: "hair-accessories",
    name: "Hair Accessories",
    description: "Claw clips, barrettes, silk scrunchies and pins — built to stay put.",
    seoDescription:
      "Our hair accessories are designed around real hair and real days. Claw clips come in two spring strengths — a wide grip for thick or curly hair and a gentler close for fine hair. French barrettes use steel spring closures that survive handbags and gym floors. Silk scrunchies are cut from mulberry silk to hold without creasing, and our pins and combs are finished by hand so nothing snags. Everything ships from our Bengaluru studio with 15-day easy returns, and bestsellers restock weekly.",
    heroImage: px(22469099, 1600, 700),
    productIds: [
      "prod-claw-tortoise",
      "prod-barrette-french",
      "prod-scrunchie-silk",
      "prod-ties-everyday",
      "prod-pins-pearl",
      "prod-clipset-pastel",
      "prod-combkit-salon",
    ],
  },
  {
    id: "col-jewellery",
    slug: "jewellery",
    name: "Jewellery",
    description: "Everyday gold-tone hoops, drops and pendants with waterproof plating.",
    seoDescription:
      "Jewellery that earns a place in daily rotation: PVD gold-tone plating that shrugs off water and sweat, hypoallergenic posts, and shapes made for stacking rather than storing. From everyday hoops to heritage-inspired drops with pearl and stone detail, each piece ships with care notes to keep the finish looking new. Pair them with our hair accessories — the teal box means they're made to be worn together.",
    heroImage: px(10944923, 1600, 700),
    productIds: ["prod-hoops-everyday", "prod-drops-heritage", "prod-pendant-teal"],
  },
  {
    id: "col-charms",
    slug: "charms",
    name: "Charms",
    description: "Bag charms and zip charms — small hardware, real personality.",
    seoDescription:
      "Charms built for daily hardware, not display cases: lobster clasps and O-rings tested for repeated clipping and unclipping, zip-pull loops sized for real zip tabs (not just photos), and finishes that hold up against keys, coins, and the bottom of a bag. Bag charms clip onto a handle or strap ring; zip charms loop directly through a zip pull for a smaller, quieter accent. Mix metals, mix themes — that's the point.",
    heroImage: px(7723760, 1600, 700),
    productIds: [
      "prod-charm-tassel-suede",
      "prod-charm-tassel-leather",
      "prod-charm-pompom-fur",
      "prod-charm-star-enamel",
      "prod-charm-heart-enamel",
      "prod-charm-initial-letter",
      "prod-charm-pearl-cluster",
      "prod-charm-shell",
      "prod-charm-knot-braided",
      "prod-charm-bell",
      "prod-zipcharm-tassel-mini",
      "prod-zipcharm-star",
      "prod-zipcharm-heart",
      "prod-zipcharm-pearl-drop",
      "prod-zipcharm-bead-set",
      "prod-zipcharm-tag",
      "prod-zipcharm-knot",
      "prod-zipcharm-charm-trio",
      "prod-charm-keyring-tassel",
      "prod-charm-bag-strap-tag",
    ],
  },
];

export const products: Product[] = [
  // ---------------- HAIR ACCESSORIES ----------------
  {
    id: "prod-claw-tortoise",
    slug: "tortoise-grip-claw-clip",
    name: "Tortoise Grip Claw Clip",
    brand: "Savvy In Teal",
    type: "Claw Clip",
    material: "Cellulose Acetate",
    description:
      "Our signature claw clip in hand-polished cellulose acetate. A wide steel spring and long interlocking teeth hold a full twist of thick or curly hair without slipping — and without the creak of cheap plastic.",
    careInstructions:
      "Wipe with a soft dry cloth. Avoid dropping on hard floors; acetate is durable but not unbreakable. Keep away from direct heat (car dashboards, straighteners).",
    measurements: "Length: 11cm · Width: 5cm · Spring: wide-grip steel",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 649,
    mrp: 899,
    currency: "INR",
    images: [
      { url: px(33343186, 800, 1000), alt: "Neutral claw clips arranged on dark stone" },
      { url: px(20166056, 800, 1000), alt: "Claw clips styled on soft white fur" },
      { url: px(20166053, 800, 1000), alt: "Close-up of claw clip teeth and finish" },
    ],
    variants: [
      { id: "var-claw-tortoise", color: "Tortoise", colorHex: "#6b4423", sku: "SIT-CLAW-TOR-01", image: px(33343186, 800, 1000), inStock: true },
      { id: "var-claw-black", color: "Black", colorHex: "#1a1a1a", sku: "SIT-CLAW-BLK-01", image: px(20166053, 800, 1000), inStock: true },
      { id: "var-claw-champagne", color: "Champagne", colorHex: "#e8d9b5", sku: "SIT-CLAW-CHM-01", image: px(20166056, 800, 1000), inStock: false },
    ],
    collectionSlugs: ["hair-accessories"],
    isNew: true,
    isSale: true,
    inStock: true,
    tags: ["claw", "thick-hair", "bestseller"],
    // Demo: wiggling sale badge, urgency "Only N left".
    stock: 3,
    stockMode: "lowOnly",
    badgeAnimation: "wiggle",
  },
  {
    id: "prod-barrette-french",
    slug: "classic-french-barrette",
    name: "Classic French Barrette",
    brand: "Savvy In Teal",
    type: "Barrette",
    material: "Acetate + Steel",
    description:
      "The half-up workhorse. A classic French barrette with a steel spring closure that clicks shut and stays shut — from morning meeting to last local home.",
    careInstructions:
      "Wipe clean with a dry cloth. If the spring loosens over years of wear, a gentle re-bend restores the click.",
    measurements: "Length: 8cm · Closure: French steel spring",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 449,
    mrp: 599,
    currency: "INR",
    images: [
      { url: px(31854724, 800, 1000), alt: "Barrettes and clips arranged in a shell dish" },
      { url: px(7450827, 800, 1000), alt: "Barrettes worn in curly hair, portrait" },
    ],
    variants: [
      { id: "var-barrette-gold", color: "Gold", colorHex: "#d4af37", sku: "SIT-BARR-GLD-01", image: px(31854724, 800, 1000), inStock: true },
      { id: "var-barrette-tortoise", color: "Tortoise", colorHex: "#6b4423", sku: "SIT-BARR-TOR-01", image: px(7450827, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["hair-accessories"],
    isNew: false,
    isSale: true,
    inStock: true,
    tags: ["barrette", "half-up"],
    // Demo: exact stock count shown for trust.
    stock: 24,
    stockMode: "exact",
  },
  {
    id: "prod-scrunchie-silk",
    slug: "mulberry-silk-scrunchie-trio",
    name: "Mulberry Silk Scrunchie Trio",
    brand: "Savvy In Teal",
    type: "Scrunchie",
    material: "Mulberry Silk",
    description:
      "Three 22-momme mulberry silk scrunchies in a rotating set of seasonal shades. Silk glides instead of gripping, so overnight buns come down crease-free.",
    careInstructions:
      "Hand wash cold with a drop of gentle shampoo. Air dry flat, away from direct sun. Do not wring.",
    measurements: "Diameter: 10cm relaxed · Silk: 22 momme charmeuse",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 999,
    mrp: 1299,
    currency: "INR",
    images: [
      { url: px(37195179, 800, 1000), alt: "Stack of silk scrunchies in soft light" },
      { url: px(31253361, 800, 1000), alt: "Satin scrunchies in warm red tones" },
    ],
    variants: [
      { id: "var-scrunchie-neutrals", color: "The Neutrals", colorHex: "#cbb9a4", sku: "SIT-SCRN-NEU-03", image: px(37195179, 800, 1000), inStock: true },
      { id: "var-scrunchie-jewel", color: "The Jewels", colorHex: "#7a1f2b", sku: "SIT-SCRN-JWL-03", image: px(31253361, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["hair-accessories"],
    isNew: true,
    isSale: false,
    inStock: true,
    tags: ["scrunchie", "silk", "gift"],
    // Demo: exact stock. No sale = no badge.
    stock: 40,
    stockMode: "exact",
  },
  {
    id: "prod-ties-everyday",
    slug: "everyday-hair-tie-set",
    name: "Everyday Hair Tie Set",
    brand: "Savvy In Teal",
    type: "Hair Tie",
    material: "Seamless Elastic",
    description:
      "Eight seamless elastics with a soft matte weave — strong enough for a gym-day ponytail, gentle enough for fine hair. The set lives happily on a wrist without leaving a mark.",
    careInstructions: "Machine wash in a laundry bag if needed; air dry. Replace when elasticity fades.",
    measurements: "Diameter: 5cm relaxed · Set of 8",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 349,
    mrp: 449,
    currency: "INR",
    images: [
      { url: px(6044137, 800, 1000), alt: "Hair ties with dried flowers on a decorative box" },
      { url: px(6044135, 800, 1000), alt: "Hair ties arranged with soft styling" },
      { url: px(6044144, 800, 1000), alt: "Hair tie set detail on textured surface" },
    ],
    variants: [
      { id: "var-ties-warm", color: "Warm Set", colorHex: "#b98a5e", sku: "SIT-TIES-WRM-08", image: px(6044137, 800, 1000), inStock: true },
      { id: "var-ties-cool", color: "Cool Set", colorHex: "#5b7a76", sku: "SIT-TIES-CLL-08", image: px(6044144, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["hair-accessories"],
    isNew: false,
    isSale: false,
    inStock: true,
    tags: ["ties", "everyday", "multipack"],
  },
  {
    id: "prod-pins-pearl",
    slug: "pearl-cluster-hair-pins",
    name: "Pearl Cluster Hair Pins",
    brand: "Savvy In Teal",
    type: "Hair Pin",
    material: "Faux Pearl + Alloy",
    description:
      "A set of five pins topped with clustered faux pearls — the fastest way to turn a plain bun into an occasion. Wedding-season favourite; sells out every October.",
    careInstructions: "Store in the pouch provided. Wipe pearls with a dry cloth; avoid perfume contact.",
    measurements: "Pin length: 6cm · Set of 5",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 799,
    mrp: 999,
    currency: "INR",
    images: [
      { url: px(27462683, 800, 1000), alt: "Pearl hair clips with baby's breath flowers" },
      { url: px(18031831, 800, 1000), alt: "Floral hair accessories flat lay" },
      { url: px(34186057, 800, 1000), alt: "Updo styled with decorative pins and flowers" },
    ],
    variants: [
      { id: "var-pins-pearl", color: "Pearl", colorHex: "#f3ede4", sku: "SIT-PINS-PRL-05", image: px(27462683, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["hair-accessories"],
    isNew: true,
    isSale: false,
    inStock: true,
    tags: ["pins", "occasion", "bridal"],
    // Demo: low-stock urgency ("sells out every October").
    stock: 2,
    stockMode: "lowOnly",
  },
  {
    id: "prod-clipset-pastel",
    slug: "pastel-mini-clip-set",
    name: "Pastel Mini Clip Set",
    brand: "Savvy In Teal",
    type: "Clip Set",
    material: "Resin",
    description:
      "Twelve mini clips in sorbet shades — for face-framing pieces, kids' hair, or pinning back a grow-out fringe. The teal one is, naturally, our favourite.",
    careInstructions: "Wipe clean. Keep the set in its tin so the small ones stop disappearing.",
    measurements: "Clip length: 3cm · Set of 12",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 499,
    mrp: 699,
    currency: "INR",
    images: [
      { url: px(8468179, 800, 1000), alt: "Colorful mini clips flat lay on pastel background" },
      { url: px(8468016, 800, 1000), alt: "Colorful clips worn in straight brown hair" },
      { url: px(33343184, 800, 1000), alt: "Clips arranged on textured surface" },
    ],
    variants: [
      { id: "var-clipset-sorbet", color: "Sorbet Mix", colorHex: "#e8b4b8", sku: "SIT-CLIP-SRB-12", image: px(8468179, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["hair-accessories"],
    isNew: false,
    isSale: true,
    inStock: true,
    tags: ["clips", "kids", "multipack"],
    // Demo: pulsing sale badge, hidden stock.
    badgeAnimation: "pulse",
  },
  {
    id: "prod-combkit-salon",
    slug: "salon-comb-and-clip-kit",
    name: "Salon Comb & Clip Kit",
    brand: "Savvy In Teal",
    type: "Kit",
    material: "Carbon Fibre + Steel",
    description:
      "The kit our stylist friends kept borrowing: two carbon-fibre combs, four sectioning clips, and a tail comb, rolled into a canvas pouch. Heat-resistant, anti-static, salon-grade.",
    careInstructions: "Wash combs in warm soapy water monthly. Canvas pouch is machine washable.",
    measurements: "Combs: 18cm & 21cm · Sectioning clips: 9cm · Pouch: 24cm roll",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 1199,
    mrp: 1499,
    currency: "INR",
    images: [
      { url: px(35013087, 800, 1000), alt: "Salon drawer with combs and sectioning clips" },
      { url: px(6188294, 800, 1000), alt: "Clips detail on textured mesh" },
    ],
    variants: [
      { id: "var-combkit-black", color: "Black", colorHex: "#1a1a1a", sku: "SIT-COMB-BLK-KIT", image: px(35013087, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["hair-accessories"],
    isNew: false,
    isSale: false,
    inStock: false,
    tags: ["kit", "salon", "tools"],
  },

  // ---------------- JEWELLERY ----------------
  {
    id: "prod-hoops-everyday",
    slug: "everyday-gold-hoops",
    name: "Everyday Gold Hoops",
    brand: "Savvy In Teal",
    type: "Earrings",
    material: "PVD Gold-Tone Steel",
    description:
      "Mid-size hoops with a click-secure closure and waterproof PVD plating. Shower in them, gym in them, forget you own them — they'll still be gold.",
    careInstructions:
      "PVD plating is water-resistant; still avoid perfume and chlorine. Wipe with the cloth provided.",
    measurements: "Diameter: 28mm · Post: hypoallergenic steel",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 1299,
    mrp: 1699,
    currency: "INR",
    images: [
      { url: px(12144990, 800, 1000), alt: "Gold hoop earrings resting on an open book" },
      { url: px(15787782, 800, 1000), alt: "Golden earrings detail on book page" },
    ],
    variants: [
      { id: "var-hoops-gold", color: "Gold", colorHex: "#d4af37", sku: "SIT-HOOP-GLD-28", image: px(12144990, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["jewellery"],
    isNew: true,
    isSale: true,
    inStock: true,
    tags: ["earrings", "hoops", "waterproof"],
  },
  {
    id: "prod-drops-heritage",
    slug: "heritage-drop-earrings",
    name: "Heritage Drop Earrings",
    brand: "Savvy In Teal",
    type: "Earrings",
    material: "Alloy + Pearl + Stone",
    description:
      "Occasion drops with pearl and green-stone detail, drawn from heritage jewellery silhouettes. Heavier in look than on the ear — the lever back carries the weight.",
    careInstructions: "Store flat in the box. Wipe after wear; keep away from moisture and perfume.",
    measurements: "Drop length: 55mm · Closure: lever back",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 1899,
    mrp: 2499,
    currency: "INR",
    images: [
      { url: px(13595793, 800, 1000), alt: "Gold drop earrings with emerald beads and pearls" },
      { url: px(32989030, 800, 1000), alt: "Chandelier earrings on beige background" },
    ],
    variants: [
      { id: "var-drops-emerald", color: "Emerald", colorHex: "#2e6b4f", sku: "SIT-DROP-EMR-01", image: px(13595793, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["jewellery"],
    isNew: false,
    isSale: false,
    inStock: true,
    tags: ["earrings", "occasion", "heritage"],
  },
  {
    id: "prod-pendant-teal",
    slug: "signature-teal-pendant",
    name: "Signature Teal Pendant",
    brand: "Savvy In Teal",
    type: "Necklace",
    material: "PVD Gold-Tone + Enamel",
    description:
      "Our namesake piece: a small enamel pendant in the house teal on a fine gold-tone chain. The one we put in every gift order's photo.",
    careInstructions: "Wipe gently; enamel resists scratching but not impact. Fasten the clasp before storing.",
    measurements: "Chain: 45cm + 5cm extender · Pendant: 12mm",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 1499,
    mrp: 1999,
    currency: "INR",
    images: [
      { url: px(32780784, 800, 1000), alt: "Gold pendant necklace styled on fabric" },
      { url: px(10944923, 800, 1000), alt: "Woman wearing layered gold jewellery" },
    ],
    variants: [
      { id: "var-pendant-teal", color: "Teal", colorHex: "#1f6f6b", sku: "SIT-PNDT-TEA-01", image: px(32780784, 800, 1000), inStock: true },
      { id: "var-pendant-blush", color: "Blush", colorHex: "#e8b4b8", sku: "SIT-PNDT-BLS-01", image: px(10944923, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["jewellery"],
    isNew: true,
    isSale: false,
    inStock: true,
    tags: ["necklace", "signature", "gift"],
  },

  // ---------------- CHARMS (bag charms + zip charms) ----------------
  {
    id: "prod-charm-tassel-suede",
    slug: "suede-tassel-bag-charm",
    name: "Suede Tassel Bag Charm",
    brand: "Savvy In Teal",
    type: "Bag Charm",
    material: "Genuine Suede + Brass-Plated Clasp",
    description:
      "A full suede tassel on a lobster clasp rated for daily clip-and-unclip, not just a display shelf. Clips onto any handle ring or D-loop.",
    careInstructions: "Spot clean with a dry suede brush. Keep away from rain — suede watermarks.",
    measurements: "Tassel length: 9cm · Clasp: brass-plated lobster",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 349,
    mrp: 449,
    currency: "INR",
    images: [
      { url: px(7723760, 800, 1000), alt: "Suede tassel bag charm on light surface" },
      { url: px(7723801, 800, 1000), alt: "Tassel charm detail, clasp visible" },
    ],
    variants: [
      { id: "var-charmtassel-suede-tan", color: "Tan", colorHex: "#c8a165", sku: "SIT-CHRM-TAN-01", image: px(7723760, 800, 1000), inStock: true },
      { id: "var-charmtassel-suede-black", color: "Black", colorHex: "#1a1a1a", sku: "SIT-CHRM-BLK-01", image: px(7723801, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: true,
    isSale: false,
    inStock: true,
    tags: ["bag-charm", "tassel", "suede"],
  },
  {
    id: "prod-charm-tassel-leather",
    slug: "leather-tassel-bag-charm",
    name: "Leather Tassel Bag Charm",
    brand: "Savvy In Teal",
    type: "Bag Charm",
    material: "Vegetable-Tanned Leather + Steel Clasp",
    description:
      "Thinner-cut leather fringe than our suede version, so it swings instead of sitting flat. Steel clasp, not brass — holds up on heavier work totes.",
    careInstructions: "Wipe with a dry cloth. Leather darkens slightly with age — that's patina, not damage.",
    measurements: "Tassel length: 10cm · Clasp: stainless steel lobster",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 399,
    mrp: 499,
    currency: "INR",
    images: [
      { url: px(7723744, 800, 1000), alt: "Leather tassel charm close-up" },
      { url: px(7723756, 800, 1000), alt: "Leather tassel charm on bag handle" },
    ],
    variants: [
      { id: "var-charmleather-cognac", color: "Cognac", colorHex: "#a5622f", sku: "SIT-CHRM-COG-01", image: px(7723744, 800, 1000), inStock: true },
      { id: "var-charmleather-black", color: "Black", colorHex: "#1a1a1a", sku: "SIT-CHRM-LBLK-01", image: px(7723756, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: false,
    isSale: false,
    inStock: true,
    tags: ["bag-charm", "tassel", "leather"],
  },
  {
    id: "prod-charm-pompom-fur",
    slug: "faux-fur-pompom-charm",
    name: "Faux Fur Pompom Charm",
    brand: "Savvy In Teal",
    type: "Bag Charm",
    material: "Faux Fur + Alloy Clasp",
    description:
      "A soft pompom on a short chain link — the one that gets asked about. Faux fur, cruelty-free, brushed back to shape after a squeeze.",
    careInstructions: "Brush gently with a soft comb if flattened. Keep dry; faux fur mats when wet.",
    measurements: "Pompom diameter: 7cm · Chain drop: 4cm",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 299,
    mrp: 399,
    currency: "INR",
    images: [
      { url: px(13252923, 800, 1000), alt: "Fluffy pompom bag charm detail" },
      { url: px(7842612, 800, 1000), alt: "Pompom charm styled on bag" },
    ],
    variants: [
      { id: "var-pompom-ivory", color: "Ivory", colorHex: "#f2ead6", sku: "SIT-POMP-IVO-01", image: px(13252923, 800, 1000), inStock: true },
      { id: "var-pompom-blush", color: "Blush", colorHex: "#e8b4b8", sku: "SIT-POMP-BLS-01", image: px(7842612, 800, 1000), inStock: true },
      { id: "var-pompom-grey", color: "Grey", colorHex: "#8a8a8a", sku: "SIT-POMP-GRY-01", image: px(13252923, 800, 1000), inStock: false },
    ],
    collectionSlugs: ["charms"],
    isNew: true,
    isSale: false,
    inStock: true,
    tags: ["bag-charm", "pompom", "fur"],
    badgeAnimation: "wiggle",
  },
  {
    id: "prod-charm-star-enamel",
    slug: "enamel-star-bag-charm",
    name: "Enamel Star Bag Charm",
    brand: "Savvy In Teal",
    type: "Bag Charm",
    material: "Hard Enamel + Gold-Tone Alloy",
    description:
      "A hard-enamel star, filled edge to edge so the colour won't chip the way soft enamel does. Clips flat against the bag rather than swinging into the way.",
    careInstructions: "Wipe with a dry cloth. Avoid nail polish remover or alcohol wipes near the enamel fill.",
    measurements: "Star width: 3cm · Clasp: gold-tone lobster",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 249,
    mrp: 299,
    currency: "INR",
    images: [
      { url: px(28263466, 800, 1000), alt: "Star charm pendant close-up" },
    ],
    variants: [
      { id: "var-starcharm-gold", color: "Gold", colorHex: "#d4af37", sku: "SIT-STAR-GLD-01", image: px(28263466, 800, 1000), inStock: true },
      { id: "var-starcharm-silver", color: "Silver", colorHex: "#c0c0c0", sku: "SIT-STAR-SLV-01", image: px(28263466, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: false,
    isSale: false,
    inStock: true,
    tags: ["bag-charm", "enamel", "star"],
  },
  {
    id: "prod-charm-heart-enamel",
    slug: "enamel-heart-bag-charm",
    name: "Enamel Heart Bag Charm",
    brand: "Savvy In Teal",
    type: "Bag Charm",
    material: "Hard Enamel + Gold-Tone Alloy",
    description:
      "Same hard-enamel fill as our star charm, in a heart cut. A small, unfussy way to personalise a plain tote or laptop bag.",
    careInstructions: "Wipe with a dry cloth. Avoid nail polish remover or alcohol wipes near the enamel fill.",
    measurements: "Heart width: 2.8cm · Clasp: gold-tone lobster",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 249,
    mrp: 299,
    currency: "INR",
    images: [
      { url: px(10845718, 800, 1000), alt: "Heart charm with gold chain detail" },
    ],
    variants: [
      { id: "var-heartcharm-red", color: "Red", colorHex: "#a5222f", sku: "SIT-HEART-RED-01", image: px(10845718, 800, 1000), inStock: true },
      { id: "var-heartcharm-pink", color: "Pink", colorHex: "#e8b4b8", sku: "SIT-HEART-PNK-01", image: px(10845718, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: false,
    isSale: true,
    inStock: true,
    tags: ["bag-charm", "enamel", "heart"],
  },
  {
    id: "prod-charm-initial-letter",
    slug: "initial-letter-bag-charm",
    name: "Initial Letter Bag Charm",
    brand: "Savvy In Teal",
    type: "Bag Charm",
    material: "Gold-Tone Alloy",
    description:
      "One block letter, sized to actually read from arm's length rather than disappear against the leather. Pick the initial at checkout.",
    careInstructions: "Wipe with a dry cloth. Store separately to avoid scratching the plating.",
    measurements: "Letter height: 2.5cm · Clasp: gold-tone lobster",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 299,
    mrp: 349,
    currency: "INR",
    images: [
      { url: px(25283498, 800, 1000), alt: "Gold letter pendant styled shoot" },
    ],
    variants: [
      { id: "var-initial-gold", color: "Gold", colorHex: "#d4af37", sku: "SIT-INIT-GLD-01", image: px(25283498, 800, 1000), inStock: true },
      { id: "var-initial-silver", color: "Silver", colorHex: "#c0c0c0", sku: "SIT-INIT-SLV-01", image: px(25283498, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: true,
    isSale: false,
    inStock: true,
    tags: ["bag-charm", "initial", "personalised"],
  },
  {
    id: "prod-charm-pearl-cluster",
    slug: "pearl-cluster-bag-charm",
    name: "Pearl Cluster Bag Charm",
    brand: "Savvy In Teal",
    type: "Bag Charm",
    material: "Faux Pearl + Gold-Tone Alloy",
    description:
      "A cluster of graduated faux pearls on a short gold-tone chain — dresses up a plain black bag for a wedding-season lunch without looking like it's trying.",
    careInstructions: "Wipe pearls with a dry cloth; avoid perfume contact.",
    measurements: "Cluster width: 4cm · Chain drop: 5cm",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 349,
    mrp: 449,
    currency: "INR",
    images: [
      { url: px(20768646, 800, 1000), alt: "Pearl cluster charm on fabric" },
      { url: px(20768643, 800, 1000), alt: "Pearl charm detail shot" },
    ],
    variants: [
      { id: "var-pearlcluster-white", color: "Ivory Pearl", colorHex: "#f2ead6", sku: "SIT-PRLC-IVO-01", image: px(20768646, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: false,
    isSale: false,
    inStock: true,
    tags: ["bag-charm", "pearl", "occasion"],
  },
  {
    id: "prod-charm-shell",
    slug: "seashell-bag-charm",
    name: "Seashell Bag Charm",
    brand: "Savvy In Teal",
    type: "Bag Charm",
    material: "Natural Shell + Brass-Plated Alloy",
    description:
      "A real natural shell, not resin-cast — so no two are perfectly identical. Pairs with the raffia-and-linen bags everyone brings out for summer.",
    careInstructions: "Wipe with a damp cloth occasionally. Natural shell may show minor texture variation.",
    measurements: "Shell length: 4-5cm (natural variation) · Clasp: brass-plated lobster",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 279,
    mrp: 349,
    currency: "INR",
    images: [
      { url: px(34678537, 800, 1000), alt: "Natural shell charm with gold detail" },
    ],
    variants: [
      { id: "var-shell-natural", color: "Natural", colorHex: "#e8dcc4", sku: "SIT-SHEL-NAT-01", image: px(34678537, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: true,
    isSale: false,
    inStock: true,
    tags: ["bag-charm", "shell", "summer"],
  },
  {
    id: "prod-charm-knot-braided",
    slug: "braided-knot-bag-charm",
    name: "Braided Knot Bag Charm",
    brand: "Savvy In Teal",
    type: "Bag Charm",
    material: "Braided Cotton Cord + Steel Clasp",
    description:
      "A hand-braided cotton cord tied into a Celtic knot — no metal to tarnish, no fur to flatten. The one charm that survives a monsoon commute unbothered.",
    careInstructions: "Wipe or rinse with water if muddy; air dry. Colour may fade slightly with years of sun exposure.",
    measurements: "Knot diameter: 3.5cm · Clasp: stainless steel lobster",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 199,
    mrp: 249,
    currency: "INR",
    images: [
      { url: px(37401697, 800, 1000), alt: "Braided cord charm detail" },
    ],
    variants: [
      { id: "var-knot-navy", color: "Navy", colorHex: "#26344d", sku: "SIT-KNOT-NVY-01", image: px(37401697, 800, 1000), inStock: true },
      { id: "var-knot-rust", color: "Rust", colorHex: "#a5622f", sku: "SIT-KNOT-RST-01", image: px(37401697, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: false,
    isSale: false,
    inStock: true,
    tags: ["bag-charm", "braided", "monsoon-proof"],
  },
  {
    id: "prod-charm-bell",
    slug: "brass-bell-bag-charm",
    name: "Brass Bell Bag Charm",
    brand: "Savvy In Teal",
    type: "Bag Charm",
    material: "Solid Brass",
    description:
      "A small solid-brass bell with a soft, low chime — quieter than it looks, so it won't announce every step. Ages into a warm patina rather than flaking.",
    careInstructions: "Polish occasionally with a brass cloth if you want to keep the shine; leave as-is for natural patina.",
    measurements: "Bell height: 2cm · Clasp: brass lobster",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 229,
    mrp: 279,
    currency: "INR",
    images: [
      { url: px(35270148, 800, 1000), alt: "Brass bell charm on display" },
    ],
    variants: [
      { id: "var-bell-brass", color: "Brass", colorHex: "#b5892c", sku: "SIT-BELL-BRS-01", image: px(35270148, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: false,
    isSale: false,
    inStock: true,
    tags: ["bag-charm", "brass", "minimal"],
  },
  {
    id: "prod-zipcharm-tassel-mini",
    slug: "mini-tassel-zip-charm",
    name: "Mini Tassel Zip Charm",
    brand: "Savvy In Teal",
    type: "Zip Charm",
    material: "Silk Thread + Alloy Loop",
    description:
      "A pocket-size silk-thread tassel that loops straight through the zip pull — no clasp to fumble with on a moving train. Built for jackets, pouches, and pencil cases alike.",
    careInstructions: "Wipe with a dry cloth. Loop is fixed, not removable — thread through before attaching to zips permanently in use.",
    measurements: "Tassel length: 3.5cm · Loop: 8mm alloy ring",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 149,
    mrp: 199,
    currency: "INR",
    images: [
      { url: px(37543454, 800, 1000), alt: "Mini tassel zip charm detail" },
    ],
    variants: [
      { id: "var-zipmini-teal", color: "Teal", colorHex: "#1f6f6b", sku: "SIT-ZTAS-TEA-01", image: px(37543454, 800, 1000), inStock: true },
      { id: "var-zipmini-gold", color: "Gold", colorHex: "#d4af37", sku: "SIT-ZTAS-GLD-01", image: px(37543454, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: true,
    isSale: false,
    inStock: true,
    tags: ["zip-charm", "tassel", "mini"],
  },
  {
    id: "prod-zipcharm-star",
    slug: "star-zip-charm",
    name: "Star Zip Charm",
    brand: "Savvy In Teal",
    type: "Zip Charm",
    material: "Gold-Tone Alloy",
    description:
      "A flat star pull, sized to sit close against the zip so it doesn't catch on jacket linings. Simple enough for a work bag, playful enough for a backpack.",
    careInstructions: "Wipe with a dry cloth.",
    measurements: "Star width: 1.8cm · Loop: 6mm alloy ring",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 129,
    mrp: 159,
    currency: "INR",
    images: [
      { url: px(18409137, 800, 1000), alt: "Small star charm zip pull" },
    ],
    variants: [
      { id: "var-zipstar-gold", color: "Gold", colorHex: "#d4af37", sku: "SIT-ZSTR-GLD-01", image: px(18409137, 800, 1000), inStock: true },
      { id: "var-zipstar-silver", color: "Silver", colorHex: "#c0c0c0", sku: "SIT-ZSTR-SLV-01", image: px(18409137, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: false,
    isSale: false,
    inStock: true,
    tags: ["zip-charm", "star", "mini"],
  },
  {
    id: "prod-zipcharm-heart",
    slug: "heart-zip-charm",
    name: "Heart Zip Charm",
    brand: "Savvy In Teal",
    type: "Zip Charm",
    material: "Gold-Tone Alloy",
    description:
      "The heart-shaped counterpart to our star zip charm — same flat, snag-free profile, same easy loop-through fit.",
    careInstructions: "Wipe with a dry cloth.",
    measurements: "Heart width: 1.7cm · Loop: 6mm alloy ring",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 129,
    mrp: 159,
    currency: "INR",
    images: [
      { url: px(15862148, 800, 1000), alt: "Small heart charm zip pull" },
    ],
    variants: [
      { id: "var-zipheart-gold", color: "Gold", colorHex: "#d4af37", sku: "SIT-ZHRT-GLD-01", image: px(15862148, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: false,
    isSale: false,
    inStock: true,
    tags: ["zip-charm", "heart", "mini"],
  },
  {
    id: "prod-zipcharm-pearl-drop",
    slug: "pearl-drop-zip-charm",
    name: "Pearl Drop Zip Charm",
    brand: "Savvy In Teal",
    type: "Zip Charm",
    material: "Faux Pearl + Alloy",
    description:
      "A single faux pearl drop on a fine loop — the quiet upgrade for a work tote's front pocket zip.",
    careInstructions: "Wipe pearl with a dry cloth.",
    measurements: "Drop length: 2.2cm · Loop: 6mm alloy ring",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 139,
    mrp: 179,
    currency: "INR",
    images: [
      { url: px(30071153, 800, 1000), alt: "Pearl drop charm zip pull" },
    ],
    variants: [
      { id: "var-zippearl-ivory", color: "Ivory", colorHex: "#f2ead6", sku: "SIT-ZPRL-IVO-01", image: px(30071153, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: true,
    isSale: false,
    inStock: true,
    tags: ["zip-charm", "pearl", "mini"],
  },
  {
    id: "prod-zipcharm-bead-set",
    slug: "beaded-zip-charm-set",
    name: "Beaded Zip Charm Set",
    brand: "Savvy In Teal",
    type: "Zip Charm",
    material: "Glass Beads + Alloy Loops",
    description:
      "A set of three glass-bead zip pulls in a rotating seasonal colourway — one for the jacket, one for the backpack, one to lose and not mind.",
    careInstructions: "Wipe with a dry cloth.",
    measurements: "Bead diameter: 8mm · Set of 3, each on its own loop",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 179,
    mrp: 229,
    currency: "INR",
    images: [
      { url: px(6953181, 800, 1000), alt: "Set of beaded zip charms" },
    ],
    variants: [
      { id: "var-beadset-jewel", color: "Jewel Mix", colorHex: "#7a1f2b", sku: "SIT-BEAD-JWL-03", image: px(6953181, 800, 1000), inStock: true },
      { id: "var-beadset-pastel", color: "Pastel Mix", colorHex: "#e8b4b8", sku: "SIT-BEAD-PST-03", image: px(6953181, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: false,
    isSale: false,
    inStock: true,
    tags: ["zip-charm", "beads", "multipack"],
  },
  {
    id: "prod-zipcharm-tag",
    slug: "engraved-tag-zip-charm",
    name: "Engraved Tag Zip Charm",
    brand: "Savvy In Teal",
    type: "Zip Charm",
    material: "Brass-Plated Alloy",
    description:
      "A flat rectangular tag, left blank for you to have engraved locally, or worn as-is for the shape alone. Comes on a loop, not a clasp — permanent once fitted.",
    careInstructions: "Wipe with a dry cloth.",
    measurements: "Tag: 2.5cm x 1cm · Loop: 6mm alloy ring",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 159,
    mrp: 199,
    currency: "INR",
    images: [
      { url: px(27498756, 800, 1000), alt: "Blank engravable tag charm" },
    ],
    variants: [
      { id: "var-tag-gold", color: "Gold", colorHex: "#d4af37", sku: "SIT-ZTAG-GLD-01", image: px(27498756, 800, 1000), inStock: true },
      { id: "var-tag-silver", color: "Silver", colorHex: "#c0c0c0", sku: "SIT-ZTAG-SLV-01", image: px(27498756, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: false,
    isSale: false,
    inStock: true,
    tags: ["zip-charm", "tag", "engravable"],
  },
  {
    id: "prod-zipcharm-knot",
    slug: "knot-zip-charm",
    name: "Knot Zip Charm",
    brand: "Savvy In Teal",
    type: "Zip Charm",
    material: "Braided Cord + Alloy Loop",
    description:
      "The pocket-size version of our braided bag charm — same cotton cord knot, scaled down to loop through a zip pull instead of a handle ring.",
    careInstructions: "Wipe or rinse with water if muddy; air dry.",
    measurements: "Knot diameter: 1.8cm · Loop: 6mm alloy ring",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 119,
    mrp: 149,
    currency: "INR",
    images: [
      { url: px(8795282, 800, 1000), alt: "Small knot charm zip pull" },
    ],
    variants: [
      { id: "var-zipknot-navy", color: "Navy", colorHex: "#26344d", sku: "SIT-ZKNT-NVY-01", image: px(8795282, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: false,
    isSale: false,
    inStock: true,
    tags: ["zip-charm", "braided", "mini"],
  },
  {
    id: "prod-zipcharm-charm-trio",
    slug: "charm-trio-zip-pull",
    name: "Charm Trio Zip Pull",
    brand: "Savvy In Teal",
    type: "Zip Charm",
    material: "Mixed Alloy + Enamel",
    description:
      "Three mini charms — a star, a dot, and a bar — clustered on one loop so a single zip pull carries all the detail our single-charm styles split across three.",
    careInstructions: "Wipe with a dry cloth.",
    measurements: "Cluster width: 2.5cm · Loop: 8mm alloy ring",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 189,
    mrp: 239,
    currency: "INR",
    images: [
      { url: px(5820205, 800, 1000), alt: "Trio of mini charms on one loop" },
    ],
    variants: [
      { id: "var-trio-gold", color: "Gold Mix", colorHex: "#d4af37", sku: "SIT-ZTRI-GLD-01", image: px(5820205, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: true,
    isSale: false,
    inStock: true,
    tags: ["zip-charm", "trio", "mixed"],
  },
  {
    id: "prod-charm-keyring-tassel",
    slug: "tassel-keyring-charm",
    name: "Tassel Keyring Charm",
    brand: "Savvy In Teal",
    type: "Bag Charm",
    material: "Leather Tassel + Steel Keyring",
    description:
      "Doubles as a keyring or a bag charm — a wider steel split ring instead of a lobster clasp, so it holds keys without them slipping loose in a bag's bottom pocket.",
    careInstructions: "Wipe with a dry cloth. Steel ring is rust-resistant but not waterproof — dry promptly if it gets wet.",
    measurements: "Tassel length: 8cm · Ring: 25mm steel split ring",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 329,
    mrp: 399,
    currency: "INR",
    images: [
      { url: px(32835562, 800, 1000), alt: "Tassel keyring charm on keys" },
    ],
    variants: [
      { id: "var-keyring-cognac", color: "Cognac", colorHex: "#a5622f", sku: "SIT-KEYR-COG-01", image: px(32835562, 800, 1000), inStock: true },
      { id: "var-keyring-black", color: "Black", colorHex: "#1a1a1a", sku: "SIT-KEYR-BLK-01", image: px(32835562, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: false,
    isSale: false,
    inStock: true,
    tags: ["bag-charm", "keyring", "leather"],
  },
  {
    id: "prod-charm-bag-strap-tag",
    slug: "bag-strap-id-tag-charm",
    name: "Bag Strap ID Tag Charm",
    brand: "Savvy In Teal",
    type: "Bag Charm",
    material: "Leather + Brass-Plated Hardware",
    description:
      "A leather luggage-style tag that wraps and snaps around a bag strap rather than clipping to a ring — stays put on backpacks with no obvious charm loop.",
    careInstructions: "Wipe with a dry cloth. Leather darkens slightly with age — that's patina, not damage.",
    measurements: "Tag: 6cm x 3cm · Strap fit: up to 3cm wide",
    shippingInfo: "Ships within 2 business days. Free shipping over ₹1,499. 15-day easy returns.",
    price: 379,
    mrp: 449,
    currency: "INR",
    images: [
      { url: px(12505531, 800, 1000), alt: "Leather bag strap tag charm" },
    ],
    variants: [
      { id: "var-straptag-tan", color: "Tan", colorHex: "#c8a165", sku: "SIT-STAG-TAN-01", image: px(12505531, 800, 1000), inStock: true },
      { id: "var-straptag-black", color: "Black", colorHex: "#1a1a1a", sku: "SIT-STAG-BLK-01", image: px(12505531, 800, 1000), inStock: true },
    ],
    collectionSlugs: ["charms"],
    isNew: false,
    isSale: false,
    inStock: true,
    tags: ["bag-charm", "leather", "strap"],
  },
];

// ---------- Lookup helpers (used by lib/api.ts fallbacks) ----------

export function getCollectionBySlug(slug: string): Collection | undefined {
  return collections.find((collection) => collection.slug === slug);
}

export function getProductsByCollectionSlug(slug: string): Product[] {
  return products.filter((product) => product.collectionSlugs.includes(slug));
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug);
}
